theme: jekyll-theme-cayman
title: Garrett Kocian
description: Full Stack Software Engineer
github_username:      gk1041
linkedin_username:    garrettkocian
url_master_branch: https://github.com/gk1041/gk1041.github.io/blob/master/
url_master_download: https://github.com/gk1041/gk1041.github.io/raw/master/
resume_name:  Resume_17_07.pdf
